//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class ModeSelectsView : ViewBase
{
    
    public UnityEngine.UI.Text Start;
    
    public UnityEngine.UI.Text Extra_Start;
    
    public UnityEngine.UI.Text Practice_Start;
    
    public UnityEngine.UI.Text Replay;
    
    public UnityEngine.UI.Text Result;
    
    public UnityEngine.UI.Text Music_Room;
    
    public UnityEngine.UI.Text Option;
    
    public UnityEngine.UI.Text Quit;
    
    public UnityEngine.UI.Text Description;
}
